"""

Basic configuration file for the project.

"""

__author__ = 'Neal Dunkinson, Joe Mullen'
__version__ = '0.1'

DATABASE_CONFIG = {
    'host'    : 'localhost',
    'dbname'  : 'company',
    'user'    : 'user',
    'password': 'password',
    'port'    : 3306
}
MARKET_SYMBOL = 'LON'
PERIOD = '1M'
INTERVAL = 86400
STOCKS = {
    'III' : '3I GRP.',
    'ABF' : 'A.B.FOOD',
    'ADM' : 'ADMIRAL GRP',
    'AAL' : 'ANGLO AMERICAN',
    'ANTO': 'ANTOFAGASTA',
    'AHT' : 'ASHTEAD GRP.',
    'AZN' : 'ASTRAZENECA',
    'AV.' : 'AVIVA',
    'BAB' : 'BABCOCK INTL',
    'BA.' : 'BAE SYS.',
    'BARC': 'BARCLAYS',
    'BDEV': 'BARRATT DEVEL.',
    'BLT' : 'BHP BILLITON',
    'BP.' : 'BP',
    'BATS': 'BR.AMER.TOB.',
    'BLND': 'BR.LAND',
    'BT.A': 'BT GROUP',
    'BNZL': 'BUNZL',
    'BRBY': 'BURBERRY GRP',
    'CCL' : 'CARNIVAL',
    'CNA' : 'CENTRICA',
    'CCH' : 'COCACOLA HBC AG',
    'CPG' : 'COMPASS GROUP',
    'CTEC': 'CONVATEC',
    'CRH' : 'CRH',
    'CRDA': 'CRODA INTL.',
    'DCC' : 'DCC',
    'DGE' : 'DIAGEO',
    'DLG' : 'DIRECT LINE',
    'EZJ' : 'EASYJET',
    'EXPN': 'EXPERIAN',
    'FERG': 'FERGUSON',
    'FRES': 'FRESNILLO',
    'GFS' : 'G4S',
    'GKN' : 'GKN',
    'GSK' : 'GLAXOSMITHKLINE',
    'GLEN': 'GLENCORE',
    'HMSO': 'HAMMERSON',
    'HL.' : 'HARGREAVES LANS',
    'HSBA': 'HSBC HLDGS.UK',
    'IMB' : 'IMP.BRANDS',
    'INF' : 'INFORMA',
    'IHG' : 'INTERCON. HOTEL',
    'ITRK': 'INTERTEK GROUP',
    'IAG' : 'INTL CONSOL AIR',
    'ITV' : 'ITV',
    'JMAT': 'JOHNSON MATTHEY',
    'KGF' : 'KINGFISHER',
    'LAND': 'LAND SECS.',
    'LGEN': 'LEGAL&GEN.',
    'LLOY': 'LLOYDS GRP.',
    'LSE' : 'LON.STK.EXCH',
    'MKS' : 'MARKS & SP.',
    'MDC' : 'MEDICLINIC',
    'MERL': 'MERLIN',
    'MNDI': 'MONDI',
    'MRW' : 'MORRISON (WM)',
    'NG.' : 'NATIONAL GRID',
    'NXT' : 'NEXT',
    'OML' : 'OLD MUTUAL',
    'IMB' : 'IMP.BRANDS',
    'INF' : 'INFORMA',
    'IHG' : 'INTERCON. HOTEL',
    'ITRK': 'INTERTEK GROUP',
    'IAG' : 'INTL CONSOL AIR',
    'ITV' : 'ITV',
    'JMAT': 'JOHNSON MATTHEY',
    'KGF' : 'KINGFISHER',
    'LAND': 'LAND SECS.',
    'LGEN': 'LEGAL&GEN.',
    'LLOY': 'LLOYDS GRP.',
    'LSE' : 'LON.STK.EXCH',
    'MKS' : 'MARKS & SP.',
    'MDC' : 'MEDICLINIC',
    'MERL': 'MERLIN',
    'MNDI': 'MONDI',
    'MRW' : 'MORRISON (WM)',
    'NG.' : 'NATIONAL GRID',
    'NXT' : 'NEXT',
    'OML' : 'OLD MUTUAL',
    'SGRO': 'SEGRO',
    'SVT' : 'SEVERN TRENT',
    'SHP' : 'SHIRE',
    'SKY' : 'SKY PLC',
    'SN.' : 'SMITH&NEPHEW',
    'SMIN': 'SMITHS GROUP',
    'SKG' : 'SMURFIT KAP.',
    'SSE' : 'SSE',
    'STJ' : 'ST.JAMES\'S PLAC',
    'STAN': 'STAND.CHART.',
    'SLA' : 'STD LIFE ABER',
    'TW.' : 'TAYLOR WIMPEY',
    'TSCO': 'TESCO',
    'TUI' : 'TUI AG',
    'ULVR': 'UNILEVER',
    'UU.' : 'UTD. UTILITIES',
    'VOD' : 'VODAFONE GRP.',
    'WTB' : 'WHITBREAD',
    'WPG' : 'WORLDPAY GRP',
    'WPP' : 'WPP'
}
